apiVersion: apps/v1
kind: Deployment
metadata:
  name: charitystore-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charitystore
  template:
    metadata:
      labels:
        app: charitystore
    spec:
      containers:
      - name: charitystore
        image: charityngenge/charity-boutgue:5
        ports:
        - containerPort: 80
